import Head from 'next/head'
import confidantBgImage from '../public/confidant_bg.jpg'
import examAnswersImage from '../public/exam_answers_bg.jpg'
import dartImage from '../public/dart_bg.jpg'
import { CardGuide } from '../components/Homepage/CardGuide.jsx'

const cardsGuide = [
  { id: 1, title: 'confidant guide', alt: 'Confidant background image', page: 'confidants' },
  {
    id: 2,
    title: 'Quiz and Exam',
    alt: 'Quiz and Exam question background image',
    page: 'quiz_n_exam',
  },
  { id: 3, title: 'Dart guide', page: 'dart' },
]
export default function Home() {
  return (
    <div>
      <Head>
        <title>Persona 5 royal helpers</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main>
        <section className='container w-full mx-auto'>
          <div className='flex flex-col items-center flex-1 py-16'>
            <div className='text-5xl text-center'>
              Welcome to
              <p className='italic'>
                Persona <span className='text-red-500'>5</span>{' '}
                <span className='text-yellow-500'> royal</span> guides
              </p>
            </div>
            <div className='pt-10 text-xl'>What are you going to do ?</div>
          </div>
          <div className='flex flex-1 flex-wrap justify-evenly items-center gap-10 pb-10'>
            {cardsGuide.map(cardInfo => (
              <CardGuide
                key={cardInfo.id}
                title={cardInfo.title}
                alt={cardInfo.alt}
                src={
                  cardInfo.id === 1
                    ? confidantBgImage
                    : cardInfo.id === 2
                    ? examAnswersImage
                    : dartImage
                }
                page={cardInfo.page}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}

